packages:
  - '*/src'
catalog:
  '@commitlint/cli': ^19.8.0
  '@commitlint/config-conventional': ^19.8.0
  '@commitlint/cz-commitlint': ^19.8.0
  '@eslint-react/eslint-plugin': ^1.31.0
  '@eslint/config-inspector': ^1.0.2
  '@ianvs/prettier-plugin-sort-imports': ^4.4.1
  '@iconify/collections': ^1.0.526
  '@iconify/json': ^2.2.315
  '@slidev/cli': ^51.4.0
  '@slidev/client': ^51.4.0
  '@slidev/theme-default': ^0.25.0
  '@types/node': ^22.13.10
  '@types/prompts': ^2.4.9
  '@types/seedrandom': ^3.0.8
  chroma-js: ^3.1.2
  commitizen: ^4.3.1
  cross-env: ^7.0.3
  eslint: ^9.22.0
  eslint-config-flat-gitignore: ^2.1.0
  eslint-plugin-format: ^1.0.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.19
  esno: ^4.8.0
  execa: ^9.5.2
  fast-glob: ^3.3.3
  husky: ^9.1.7
  lint-staged: ^15.4.3
  markdown-it-magic-link: ^0.1.4
  playwright-chromium: ^1.51.0
  pnpm: ^10.6.2
  prettier-plugin-slidev: ^1.0.5
  prompts: ^2.4.2
  rimraf: ^6.0.1
  seedrandom: ^3.0.5
  slidev-addon-graph: ^0.1.0
  taze: ^19.0.1
  typescript: ^5.8.2
  unocss: ^66.1.0-beta.3
  uqr: ^0.1.2
  vis-data: ^7.1.9
  vis-network: ^9.1.9
  vite: ^6.2.1
  vue-router: ^4.5.0
  vue-tsc: ^2.2.8
